FROM python:3.11-slim-bookworm
RUN pip install --no-cache-dir mlflow==2.17.2
EXPOSE 5000
VOLUME ["/mlflow"]
WORKDIR /mlflow
CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "sqlite:////mlflow/mlflow.db", "--default-artifact-root", "file:///mlflow/artifacts"]
