stages:
  prepare:
    cmd: python src/prepare.py data/raw/House_Rent_10M_balanced_40cities.csv data/prepared
    deps:
      - data/raw/House_Rent_10M_balanced_40cities.csv
      - src/prepare.py
      - src/preprocess.py
    params:
      - prepare
    outs:
      - data/prepared

  train:
    cmd: python src/train.py data/prepared data/models
    deps:
      - data/prepared
      - src/train.py
    params:
      - train
    outs:
      - data/models
