prepare:
  nrows: 500000
  test_size: 0.2
  random_state: 42

train:
  n_estimators: 100
  max_depth: 20
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: sqrt
  random_state: 42
  experiment_name: House_Rent_Prediction
